# -*- coding: utf-8 -*-
"""SENAI-Python-Aula2-FOR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tcDOswv3kIEc1DbHT05HEXusiOz4CPdn
"""

valor_x = float(input("Escreva um valor para X\n"))

for x in range(4):
  resultado = (valor_x * 12)
  valor_x = resultado
  print(resultado)

"""## Faça um programa que leia 5 numeros e informe o maior numero"""

maior_numero = float('-inf') #essa e uma variavel global

for i in range(5):
 numero = float(input(f"Digite o {i+1} numero "))
if numero > maior_numero:
  maior_numero = numero

print(f"Maior numerodigitado e: {maior_numero}")

"""Fa;a um programa que verifique e mostre os numeros 1000 e 2000 (inclusive) que, quando divididos por 11 produzam resto igual a 2"""

for numero in range(1000, 2001):
 if numero % 11 == 2:
  print(numero)

"""## Faca um programa que receba um numero e usado lacos de repeticao calcule e mostre a tabuada desse numero"""

numero = int(input("Digite um numero que vc nao sabe a tabuada: "))
print(f"Tabuada de {numero}")

for contador in range(1, 11):
  resultado = numero * contador
  print(f"{numero} x {contador} = {resultado}")

"""## Faca um programa que imprima na tela os numeros de 1 a 20, um abaixo do outro> Depois modifique um programa para que ele mostre os numeros um ao lado do outro."""

for i in range(1, 21):
  print(i)

print(list(range(1,21)))